[package]
name = "channel"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
license = "Apache-2.0/MIT"

[dependencies]
coco = { path = "../coco" }
crossbeam = { path = "../crossbeam" }
rand = "0.3"
chan = "*"
parking_lot = "*"
