[package]
name = "crossbeam-epoch"
version = "0.1.0"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam-epoch"
homepage = "https://github.com/crossbeam-rs/crossbeam-epoch"
documentation = "https://docs.rs/crossbeam-epoch"
description = "Epoch-based garbage collection"
keywords = ["lock-free", "rcu", "atomic", "garbage"]
categories = ["concurrency", "memory-management"]

[features]
default = ["use_std"]
use_std = ["lazy_static"]
nightly = ["arrayvec/use_union"]
strict_gc = []

[dependencies]
arrayvec = { version = "0.4", default-features = false }
crossbeam-utils = { version = "0.1", default-features = false }
lazy_static = { version = "0.2", optional = true }
memoffset = { version = "0.1", default-features = false }
