[package]
name = "crossbeam"
version = "0.3.0"
authors = ["Aaron Turon <aturon@mozilla.com>"]
description = "Support for lock-free data structures, synchronizers, and parallel programming"
repository = "https://github.com/aturon/crossbeam"
documentation = "http://aturon.github.io/crossbeam-doc/crossbeam/"
readme = "README.md"
license = "Apache-2.0/MIT"
categories = ["concurrency", "data-structures"]

[features]
nightly = []

[dependencies]
lazy_static = "0.2"

[dev-dependencies]
rand = "0.3"
