[package]
name = "crossbeam"
# When publishing a new version:
# - Update CHANGELOG.md
# - Update README.md
# - Create "crossbeam-X.Y.Z" git tag
version = "0.7.1"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam"
homepage = "https://github.com/crossbeam-rs/crossbeam"
documentation = "https://docs.rs/crossbeam"
description = "Tools for concurrent programming"
keywords = ["atomic", "garbage", "non-blocking", "lock-free", "rcu"]
categories = ["concurrency", "memory-management", "data-structures", "no-std"]
exclude = ["/ci/*", "/.travis.yml", "/bors.toml"]

[badges]
travis-ci = { repository = "crossbeam-rs/crossbeam" }

[features]
default = ["std"]
nightly = ["crossbeam-epoch/nightly", "crossbeam-utils/nightly"]
std = ["crossbeam-epoch/std", "crossbeam-utils/std"]

[dependencies]
cfg-if = "0.1.2"

[dependencies.crossbeam-channel]
version = "0.3.7"
path = "./crossbeam-channel"

[dependencies.crossbeam-deque]
version = "0.7.0"
path = "./crossbeam-deque"

[dependencies.crossbeam-epoch]
version = "0.7.1"
path = "./crossbeam-epoch"

[dependencies.crossbeam-queue]
version = "0.1.0"
path = "./crossbeam-queue"

[dependencies.crossbeam-utils]
version = "0.6.5"
path = "./crossbeam-utils"

[dev-dependencies]
rand = "0.6"

[workspace]
members = [
  ".",
  "crossbeam-channel",
  "crossbeam-channel/benchmarks",
  "crossbeam-deque",
  "crossbeam-epoch",
  "crossbeam-queue",
  "crossbeam-skiplist",
  "crossbeam-utils",
]
