[package]
name = "crossbeam-channel"
version = "0.1.2"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam-channel"
homepage = "https://github.com/crossbeam-rs/crossbeam-channel"
documentation = "https://docs.rs/crossbeam-channel"
description = "Multi-producer multi-consumer channels for message passing"
keywords = ["channel", "mpmc", "select", "golang", "message"]
categories = ["algorithms", "concurrency", "data-structures"]

[features]
nightly = []

[dependencies]
crossbeam = "0.3.0"
crossbeam-epoch = "0.2.0"
crossbeam-utils = "0.2.0"
parking_lot = "0.4.4"
rand = "0.3"
