[package]
name = "crossbeam-utils"
version = "0.1.0"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam-utils"
homepage = "https://github.com/crossbeam-rs/crossbeam-utils"
documentation = "https://docs.rs/crossbeam-utils"
description = "Utilities for concurrent programming"

[features]
nightly = []

[dependencies]
cfg-if = "0.1"
